### ISSUE TITLE
Download failed. Failed to connect to localhost port XXXX: Connection refused

### ISSUE THREAD

**Issue by vonpupp** [bitnami/bitnami-docker-wordpress#10]
Hello,

I am trying to load a theme [1](https://dl.dropboxusercontent.com/u/239592/bitnami-tests/wpresidence.zip) on a bitnami-wordpress image. The theme loads fine, however it has some extra dependencies bundled within the theme like revslider, when I get prompted to install the extra dependencies, I cannot install anything, I always get an error:

```
The plugin does not have a valid header.
Downloading install package from http://localhost:8081/wp-content/themes/wpresidence/libs/plugins/revslider.zip…

Download failed. Failed to connect to localhost port 8081: Connection refused
```

Could you please help me?

Thank you very much!

**Comment by aruiz14** [comment]
Hi vonpupp,

Could you let us know more details about the steps you performed before installing the theme? We have just checked a fresh launched WordPress image (bitnami/wordpress:4.4.2-3) and it works both installing the theme and the recommended plugins.

The error that is mentioned in the error is 8081, which is the port we recommend to use for configuring Apache when Varnish is configured. In this case, the Bitnami Docker image for WordPress does not enable this configuration by default. May be possible that you changed this?

Looking forward to your feedback,
Alejandro

**Comment by vonpupp** [comment]
Thanks for your reply aruiz14,

I wrote this testing docker-compose.yml file and I launched it using compose. Could you please share your compose file?

    wordpress_db:
      image: mariadb
      ports:
        - "127.0.0.1:3306:3306"
      environment:
        - MYSQL_DATABASE=wordpress
        - MYSQL_ROOT_PASSWORD=password
      volumes:
        - ./data/mysql:/var/lib/mysql

    wordpress_app:
      image: bitnami/wordpress
      links:
        - wordpress_db:mysql
      ports:
        - "127.0.0.1:8081:80"
      expose:
        - 443
        - 80
        - 22
      volumes:
        - ./data/site:/opt/bitnami/apps
      environment:
        - DB_NAME=wordpress
        - DB_PASSWORD=password
        - USER_UID=1000 # `id -u`
        - BITNAMI_APP_VERSION=4.4.2-3
        - BITNAMI_APP_USER=av
        - BITNAMI_APPLICATION_USER=av
        - BITNAMI_APPLICATION_PASSWORD=q

**Comment by prydonius** [comment]
Hi @vonpupp,

It looks like your issue is that you're forwarding `8081` to `80` in the container, so `localhost:8081` is only accessible on your docker host. Inside the container, the plugin is trying to pull from `localhost:8081`, but since nothing is accessible on that port inside the container, it fails (try `docker exec -ti wordpress curl http://localhost:8081`). The only way you can get this to work on `localhost` is to map `80` on the host to `80` inside the container - or you need to use an IP address that both the host and the container can access.

By the way, unfortunately at the moment the WordPress image cannot use an external database, so the `wordpress_db` service won't be used by the container despite your link. We are working to address this, and should have a new version soon that will enable you to use an external database container.

**Comment by vonpupp** [comment]
Thank you very much @prydonius. I will try that!

**Comment by prydonius** [comment]
@vonpupp just following up, were you able to solve your issue?

**Comment by vonpupp** [comment]
I switched to the php official docker container since it suited me better. I appreciate your follow up. Thank you very much @prydonius.

**Comment by prydonius** [comment]
No worries @vonpupp. Out of curiosity, why did the php official docker container work out better for you? Is there anything we could do to improve this container to meet your needs?

**Comment by vonpupp** [comment]
I couldn't fully try the bitnami solution due to the problems I had (I don't know much about docker). I don't need a fresh wordpress instance but a specific instance of a working wordpress (it is a migration to a docker system if you will). After everything was working I was happy enough to use that solution.

**Comment by javsalgar** [comment]
@fengfranklu some time has passed, so could you let us know how to reproduce the issue you are running into?
