### ISSUE TITLE
After recreating containers : "Error executing 'postInstallation': Cannot read property '1' of null"

### ISSUE THREAD

**Issue by damienfa** [bitnami/bitnami-docker-wordpress#128]
**Description**

After a "docker-compose down" , then a "docker-compose up", the containers will up, but wordpress will fail. Seen by a docker logs : 
```
Welcome to the Bitnami wordpress container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress/issues

nami    INFO  Initializing apache
apache  INFO  ==> Reconfiguring PID file location...
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing wordpress
wordpre INFO  WordPress has been already initialized, restoring...
🚒 Error executing 'postInstallation': Cannot read property '1' of null   
```

I can remove the file `/bitnami/wordpress/.installed` and it will work after a new `docker-compose up`.
But it doesn't seem to be the right solution...  

It's a big problem because if I want to update the bitnami/wordpress image I can't make it work anymore... 

Maybe 

**Steps to reproduce the issue:**

1. `docker-compose up`
2. Your wordpress is successfully up and working on port 80  
3. `docker-compose down` (=> containers are stopped and downed)
4. `docker-compose up` (=> relaunch everything)
5. wait 30sec
6. with `docker ps -a | grep wordpress` or `docker logs <here your wordpress container name>` you will see that the container has been killed because wordpress hasn't been successfully initialized
👎 

**Version**

- Output of `docker version`:

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: true
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.21.1, build 5a3f1a3
docker-py version: 3.3.0
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018
```

**Comment by andresbono** [comment]
Hi @damienfa, you are mentioning an update in the bitnami/wordpress image. What is the version of the container image that you had running previously and what is the version that you are trying to launch now? Maybe the problem is due to incompatibilities between both versions.

___

Could you try something to get more information about your issue? It is probably due to the container not being able to get the credentials to connect to the database from the `wp-config.php` config file. Could you execute the following command and share the output? If you have a password defined, please, in your message, obfuscate its value to something like `******`.

`docker-compose run wordpress cat /bitnami/wordpress/wp-config.php | grep "DB_"`
```
define('DB_NAME', 'bitnami_wordpress');
define('DB_USER', 'bn_wordpress');
define('DB_PASSWORD', '******');
define('DB_HOST', 'mariadb:3306');
define('DB_CHARSET', 'utf8');
define('DB_COLLATE', '');
```
___

Also, to confirm that the issue is related to the database credentials, could you add the following environment variable in your `docker-compose.yml` file?:
```diff
  wordpress:
    ...
    environment:
+     - NAMI_LOG_LEVEL=trace
```

Then, execute `docker-compose up` again. You will see a trace of the error. Could you share it?

Thanks!
-Andrés B.

**Comment by damienfa** [comment]
Hi @andresbono , 
and thanks for your answer.

I'm using the image `bitnami/wordpress:4` and I always did. (I just update temporarily my container to open ports externally and access my database from the outside).

Here is what I've got with `docker-compose run wordpress cat /bitnami/wordpress/wp-config.php | grep "DB_"` : 
```
define('DB_NAME', 'wordpress-db');
define('DB_USER', getenv('WORDPRESS_DATABASE_USER'));
define('DB_PASSWORD', getenv('WORDPRESS_DATABASE_PASSWORD') );
define('DB_HOST', 'mariadb:3306');
define('DB_CHARSET', 'utf8');
define('DB_COLLATE', '');
```
(I've changed a little bit the wp-config.php to be able to customize with Rancher-Compose)

About the NAMI_LOG_TRACE, everything goes well when I "docker-compose up" no error displayed. But when I do a `docker logs <my container name>`, I've got : 

```
Welcome to the Bitnami wordpress container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress/issues

nami    INFO  Initializing apache
apache  TRACE [restorePersistedData] Restoring /bitnami/apache/conf to /opt/bitnami/apache/conf
apache  INFO  ==> Reconfiguring PID file location...
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
php     TRACE [restorePersistedData] Restoring /bitnami/php/conf to /opt/bitnami/php/conf
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing wordpress
wordpre INFO  WordPress has been already initialized, restoring...
wordpre TRACE [restorePersistedData] Restoring /bitnami/wordpress/wp-content to /opt/bitnami/wordpress/wp-content
wordpre TRACE [restorePersistedData] Restoring /bitnami/wordpress/wp-config.php to /opt/bitnami/wordpress/wp-config.php
Error executing 'postInstallation': Cannot read property '1' of null
nami    TRACE TypeError: Error executing 'postInstallation': Cannot read property '1' of null
    at _.each (/root/.nami/components/com.bitnami.wordpress/helpers.js:184:96)
    at /opt/bitnami/nami/node_modules/lodash/index.js:29:420
    at $t (/opt/bitnami/nami/node_modules/lodash/index.js:18:441)
    at /opt/bitnami/nami/node_modules/lodash/index.js:29:232
    at Function.<anonymous> (/opt/bitnami/nami/node_modules/lodash/index.js:33:428)
    at Function.<anonymous> (/opt/bitnami/nami/node_modules/lodash/index.js:33:285)
    at Object.$app.helpers.getDatabaseProperties (/root/.nami/components/com.bitnami.wordpress/helpers.js:183:5)
    at Component.$app.postInstallation (/root/.nami/components/com.bitnami.wordpress/main.js:66:39)
    at Component.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)
    at _.each.step (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:32)
```

So... I think I get it.... 🤭

**Comment by andresbono** [comment]
That's exactly the issue.

To solve this, you can build a new image based on this one. You can modify the `helpers.js` to obtain the values of the credentials to connect to the database in a different way, from the env vars directly for example. Something like:

```
result['username'] = process.env.WORDPRESS_DATABASE_USER
```

Is that a valid option for you?

Regards,
-Andrés B.

**Comment by damienfa** [comment]
Yes, it works ! Thank you ! 

In `helpers.js`  I didn't get that `getDatabaseProperties()` is called only on restore (not on initializing). 
I've updated the `helpers.js` to make my env-vars directly returned as you mentioned.

Regards,
-Damien Fa-

**Comment by grischa** [comment]
Should configuration not better be done in a single, obvious way, and not once by environment variables, and in other cases by some file?
The current way is somewhat unintuitive. Right now I have a K8s deployment that has env vars set that are completely bogus, and it uses configuration persisted on an NFS drive that is not directly accessible other than exec-ing into the NFS containers.

Maintaining an image just for this does not seem warranted either. Why not enhance your regular expression to include getenv as an option?
How about this regular expression:
```
/^\s*define\('DB_NAME',\s*(?:(getenv)\()*'([^']*)'(?:\))*\);/
```
followed by `if (match[1] === "getenv") value = process.env[match[2]] else value = match[2]`

I am happy to make a pull request with this enhancement if you point me to where the code is on GitHub.

**Comment by andresbono** [comment]
Hi @grischa, actually, the regular process to configure the database is through environment variables that should be set on the first run of the containers. See the following section of the README.md: https://github.com/bitnami/bitnami-docker-wordpress#environment-variables

**Comment by grischa** [comment]
Thank you @andresbono. I understand how it is set up, but I don't think it is useful.

I don't see the rationale for persisting the environment variable values. Surely, no one would actually need to type them out by hand every time and wants to save effort. Any sane use of Docker will use at least a docker-compose file, but more likely a Deployment definition or helm chart values. So they are persisted already. Having the configuration persisted once is sufficient and adding this hidden magic is unnecessary and error prone.

**Comment by andresbono** [comment]
The way most applications work is by setting values in a configuration file, so the value of environment variables are going to be persisted because of the application requirements.

In other cases, the applications go through an first initialization process in which, for instance, the database is populated. Note that if you change those initial values, you may need to do a second "first initialization" and that may lead into inconsistencies and data loss.

In any case, we are going to evaluate if what you are proposing makes sense for part of the inputs of some of our applications.

**Comment by ap1969** [comment]
Hi,
I've just tried to do the same thing, using getenv() to drive the wp-config.php settings.

The file is persisted  onto block storage, and I don't really want database username/passwords etc just lying around, when they could be held in environment variables.

This is pretty basic 12-factor stuff, so I'm surprised that security settings are written permanently to a plain text file.

If you could change the way the config is read, that would be great, or make it easier to opt out of  the chunk of code that's causing the problem in helper.js?

Regards,
Andy

**Comment by andresbono** [comment]
Hi @ap1969,

We tend to not modify the way applications are configured, we just automate it. For that reason we don't usually change the way secrets are handled by the application itself.

**Comment by Rauno56** [comment]
I can totally see how the initial version could end up being implemented exactly like it is now, but I also find regexing those from an application source file, which yes, is meant to handle configuration, but due to the nature of how it's implemented is still "code", very counter-intuitive as well.

I personally think it should just be hard-coded to `getenv`, but if that's not an option for some reason, least one can expect is:

* it being documented in `wp-config.php`,
* the error message being descriptive and
* `helper.js`(which is, imho, also "modification to how the application is configured") to fall back to taking those from the environment.

If there's any chance of it landing, I'd be happy to make at least the first two into a PR.

cc: @andresbono

**Comment by andresbono** [comment]
Hi @Rauno56, thanks for sharing your point of view and offering your time to contribute with the changes. The major issue with contributions to this specific container is that the configuration logic is APACHE licensed but it is not public in GitHub or any other public code repository. We are changing that and for instance, you can see others like https://github.com/bitnami/bitnami-docker-mariadb.

We will try to evaluate and find a fix to this issue, at least improving the error message and putting a comment in the wp-config.php file as you suggest.

**Comment by Rauno56** [comment]
> that the configuration logic is APACHE licensed

That is the `helper.js` itself?

Thanks reconsidering it.

**Comment by andresbono** [comment]
The configuration logic is under `$NAMI_PREFIX/components/com.bitnami.wordpress/` in case you want to explore it.

**Comment by joancafom** [comment]
Hi @Rauno56 !

Thanks to your feedback we have implemented some new changes in our recent [release](https://github.com/bitnami/bitnami-docker-wordpress/commit/4894e2c22bda3663f21bb81657bb9d4d0d50b858). Although as @andresbono pointed out, due to the fact that the logic is not public in GitHub you can't see them directly in the commit, we have shipped the new version with an improved error message and a comment in `wp-config.php` to let the users know.

Thanks so much!

**Comment by Sfaraaah** [comment]
No we need to re-open it my phone and Facebook and all my accounts were hacked and it took me one week to get everything straightened out we need to re-open this issue and fix everything thank you

**Comment by andresbono** [comment]
Hi @Sfaraaah, what is your specific issue?

**Comment by blackwarriorxtn** [comment]
To solve this issue you have to delete the maria db volume ... seems like while Initializing it got confused with the old config 
docker-compose down
docker volume prune
docker-compose up fixed the issue for me

**Comment by miguelaeh** [comment]
Hi  @blackwarriorxtn ,
I am a bit confused about your comment. Could you elaborate which issue do you refer to?

**Comment by blackwarriorxtn** [comment]
@miguelaeh  I'm referring to the main issue
