### ISSUE TITLE
Cannot update plugins

### ISSUE THREAD

**Issue by sschimmel** [bitnami/bitnami-docker-wordpress#139]
**Description**

Plugin updates fail with error: `Update Failed: Could not create directory.`

**Steps to reproduce the issue:**

1. Open wp-admin and login
2. Go to Plugins -> Installed plugins
3. For a plugin that has an update available click on `update`
4. Wait
5. Error is produced

**Describe the results you received:**

I have a newly created setup of Wordpress based on the stable/wordpress helm chart running. There are 3 replicas running in the deployment. Persistent storage is available and bound.

The website and wp-admin panel open and work. However when I want to update a plugin to it's most recent version the installation fails with the error: `Update Failed: Could not create directory.`.

There are currently 6 plugins that have an update available and I have tried to update several. They all produce the same error.

**Describe the results you expected:**

Plugins update

**Additional information you deem important (e.g. issue happens only occasionally):**

Running on Azure Kubernetes Service with kubernetes version 1.10.5.

**Version**

- Output of `docker version`:

Kubernetes on Azure is a managed service. Docker version is unknown. Seems to be irrelevant as website is working fine.

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by marcosbc** [comment]
Hi @sschimmel,

Unfortunately we're unable to reproduce your issue. We've tried on a Minikube cluster, a self-hosted K8s cluster and Azure Kubernetes Service (using K8s version 1.10.5), and we're able to update plugins just fine.

We did the following:

- Run `helm install stable/wordpress --set replicaCount=3`.
- Once deployed, go to `/wp-admin` -> Log in -> Sidebar -> Plugins -> Installed Plugins.
- In the page listing installed plugins, we click on the "update now link", and the yellow box gets replaced with a success message.

Our AKS cluster was also run with Kubernetes 1.10.5.

Is this issue something you're able to reproduce consistently? How are you configuring your disks?

It would also help to know what happens when you run the command below inside the containers (with `kubectl exec -ti containername /bin/bash`):

    $ ls -lah /bitnami/wordpress /bitnami/wordpress/wp-content/plugins/

You should see files owned by "bitnami:daemon" or "daemon:daemon" (except for `/bitnami/wordpress/.initialized`, owned by root).

Thanks!

**Comment by sschimmel** [comment]
The storage backend used is [Azure Files](https://docs.microsoft.com/en-us/azure/storage/files/storage-files-introduction). Azure Files is available as a Storage Class. The pods have access to it using a regular Persistent Volume and Persistent Volume Claim. Access mode is set to: ReadWriteMany.

I tried again to update the plugins and all still fail on the same error.

Running `ls -lah /bitnami/wordpress /bitnami/wordpress/wp-content/plugins/` I see that all files and folders are owned by root. There were no errors during the start of the pods. Those should have been set to `bitnami:daemon` during boot of the containers, correct?

![image](https://user-images.githubusercontent.com/459456/43543979-e8e11eca-95d1-11e8-83b0-10b88e46f3d9.png)

I manually run a `chown -R bitnami:daemon wp-content` command and still the wp-content folder is owned by root:root.

There seems to be a problem with updating the ownership of the folders. I'll dig in to that.

**Comment by marcosbc** [comment]
Hi,

It definitely looks like an issue on how the volume was mounted. Let us know if you find anything.

**Comment by spinside** [comment]
Can you post the storageclass your using for Azure file?
I edited the storageclass mount options as follows and that did resolve the issue for me:

mountOptions:
 - dir_mode=0777
 - file_mode=0777
 - uid=1001
 - gid=1001

**Comment by marcosbc** [comment]
Thanks for sharing your solution @spinside! I hope this works for @sschimmel.
