### ISSUE TITLE
Support subdirectory for Site URL (WP_SITEURL, WP_HOME)

### ISSUE THREAD

**Issue by ceefour** [bitnami/bitnami-docker-wordpress#155]
**Description**

Bitnami WordPress Docker cannot be installed as a subdirectory of the domain.

**Steps to reproduce the issue:**

1. Launch WordPress using this docker
2. There is no way to configure it the blog to load at `http://domain/blog/`

**Describe the results you received:**

Blog is always at `http://domain/`

**Describe the results you expected:**

Blog can be configure to be e.g. `http://domain/blog/`

Preferably using an environment variable, e.g. `WORDPRESS_PATH` or similar

**Additional information you deem important (e.g. issue happens only occasionally):**

https://hub.docker.com/r/weseek/bitnami-wordpress-subdir/ tried to do this but it's no longer maintained.

Tried to edit this, but never made it work well (redirect problems, etc.): /bitnami/wordpress/wp-config.php :  

```
define('WP_SITEURL', 'https://heartenly.com/hot');
define('WP_HOME', 'https://heartenly.com/hot');
```

Related to #114.

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a215d7133c34aa18e3b72b4a21fd0c6136
 Built:             Fri Oct 26 23:38:29 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a/18.06.1-ce
  Built:            Fri Oct 26 23:39:57 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.77-80.57.amzn2.x86_64
Operating System: Amazon Linux 2
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 959.5MiB
Name: ip-10-0-0-174.ec2.internal
ID: NYCD:VX7J:QKMS:QOCE:ZPOB:6CRO:BEQV:LN6N:RZDG:IG6R:ARQA:GFBC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Using AWS ECS, EC2 type (not Fargate)

**Comment by javsalgar** [comment]
Hi,

I am not sure if that's something we will work in the short term, taking into account that most of the containerized deployments use solutions like Ingress in Kubernetes where they manage this kind of situations. Could you add more details about your setup?

**Comment by ceefour** [comment]
@javsalgar Having a reverse proxy is not the main issue, we can use `nginx-proxy`, API Gateway, etc.

However, since the wordpress itself thinks that it is hosted on `/`, it stubbornly redirects to `/`, even if it's hosted on `/blog/`. (it's may be possible to do content transformations etc. but that is flaky and not applicable to all reverse proxies, which can be handled by wordpress itself)

The use case is like this: https://ignitevisibility.com/why-blogs-on-subdomains-are-basically-worthless-for-seo/

If there's a main site (app), and a WordPress (blog site), it's beneficial to have them on the same domain.
So in my case, it'd be great it:

* https://heartenly.com/ -> the dynamic app
* https://heartenly.com/hot/ -> the blog

Currently I have to use https://hot.heartenly.com/ because I can't get it to work as a path.

Like described by https://ignitevisibility.com/why-blogs-on-subdomains-are-basically-worthless-for-seo/ this use case is pretty common.

**Comment by ioandev** [comment]
Hi, any update for this?

**Comment by FraPazGal** [comment]
Hi @ioandev,

There's no environment variable to configure this at the moment. That said, you can mount any custom script you want at `/docker-entrypoint-init.d` and it'll be executed during the 1st boot of the WordPress container. Using this, you can include a script that use `wp-cli` or a custom regex to adapt the `wp-config.php` automatically to use the necessary host modifying `WP_SITEURL` and `WP_HOME`.

**Comment by ioandev** [comment]
Hi @FraPazGal ,

Thank you for getting back to me on this. I've tried adding this features for an afternoon and here's what I've found.

`WP_SITEURL` and `WP_HOME` are not fully capable of handling subdirectories. The assets during installation are not there because the wp-config.php is not written yet, so sysadmins have to revert to creating the file themselves.

When trying to access /blog/wp-admin you'll get 301 redirected away from the page, even if the environment variables are set in wp-config.php.

There seems to be a part of wordpress internals that does not make use of the environment variables when it comes to prepending a subdirectory to the uri.

**Comment by FraPazGal** [comment]
Hi @ioandev,

I'm not sure I understood what you meant by your second paragraph. The scripts at `/docker-entrypoint-init.d` are run after installation, so the filesystem should already be in place. Giving the official documentation a look, another option would be to change `/opt/bitnami/wordpress/wp-content/themes/twentynineteen/functions.php` as detailed [here](https://wordpress.org/support/article/changing-the-site-url/#edit-functions-php), could you give it a try?

**Comment by marcosbc** [comment]
Hi all, we don't currently support this feature out of the box nor do we expect to. However, we just added support for WordPress Multisite in [`5.7.1-debian-10-r21`](https://github.com/bitnami/bitnami-docker-wordpress#571-debian-10-r21). By [configuring Multisite options](https://github.com/bitnami/bitnami-docker-wordpress#multisite-configuration) you can make a site be available at `/blog`.

If that is not enough for you, note that with these changes we also open sourced the initialization scripts. Now they live at the [*rootfs/* folder](https://github.com/bitnami/bitnami-docker-wordpress/tree/master/5/debian-10/rootfs/opt/bitnami/scripts) in this repo. Feel free to extend this image to use [`ensure_web_server_prefix_configuration_exists`](https://github.com/bitnami/bitnami-docker-wordpress/blob/master/5/debian-10/prebuildfs/opt/bitnami/scripts/libwebserver.sh#L285) instead of [`ensure_web_server_app_configuration_exists`](https://github.com/bitnami/bitnami-docker-wordpress/blob/master/5/debian-10/prebuildfs/opt/bitnami/scripts/libwebserver.sh#L187) in [`libwebserver.sh`](https://github.com/bitnami/bitnami-docker-wordpress/blob/master/5/debian-10/rootfs/opt/bitnami/scripts/libwordpress.sh#L638).

**Comment by thevahidal** [comment]
> By [configuring Multisite options](https://github.com/bitnami/bitnami-docker-wordpress#multisite-configuration) you can make a site be available at `/blog`.

About this part, can you explain how we can achieve that? I tried to configure multisite options but no luck yet!

**Comment by javsalgar** [comment]
Could you let us know your docker-compose file?
