### ISSUE TITLE
Feature request: Allow php.ini modifications in Kubernetes

### ISSUE THREAD

**Issue by WebSpider** [bitnami/bitnami-docker-wordpress#179]
**Description**

When using bitnami's wordpress image in docker, php.ini is non-persistent. When needing to change php.ini, for instance to raise memory allocation, max post sizes, execution times, this is lost whenever a pod is restarted

**Steps to reproduce the issue:**

1. Run the bitnami wordpress container using the helm chart
2. Modify php.ini to include various changes
3. Kill pod
4. Check new pod, changes are lost

**Describe the results you received:**

php.ini reverts to original state

**Describe the results you expected:**

Variables to persist

**Additional information you deem important (e.g. issue happens only occasionally):**

Using the latest debian image.
This is mostly an issue because setting variables in wp-config.php using syntax like:

```
ini_set( 'upload_max_filesize' , '512M' );
ini_set( 'post_max_size', '512M' );
ini_set( 'memory_limit', '256M' );
ini_set( 'max_execution_time', '300' );
ini_set( 'max_input_time', '600' );
define( 'WP_MEMORY_LIMIT', '256M' );
```

Doesn't work, the variables only get changed only when actually changing php.ini

**Version**

Helm chart version wordpress-5.12.3 with default image

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.8", GitCommit:"a89f8c11a5f4f132503edbc4918c98518fd504e3", GitTreeState:"clean", BuildDate:"2019-04-23T04:41:47Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by WebSpider** [comment]
This appears to be loosly related to #131

**Comment by marcosbc** [comment]
Hi @WebSpider, the problem with adding custom values to `php.ini` is that it has sections (which does not happen in `.properties` files), and each of these sections follow their own format. For example:

- `[PHP]`
- `[Date]`
- `[Pdo_mysql]`
- `[mail function]`
- `[exif]`

And therefore it would be really complicated to create a way to map environment variables to this file. Therefore we recommend you to [customize your own PHP container](https://github.com/bitnami/bitnami-docker-wordpress#customize-this-image).

Note that since `5.2.1-debian-9-r9` and `5.2.1-ol-7-r9` it is possible to fully customize the contents of the `php.ini` file, and the same applies for `httpd.conf`. You can find more details in the [Notable Changes](https://github.com/bitnami/bitnami-docker-wordpress#notable-changes) section. Find an example of a Dockerfile below that would change one of the properties:

```
FROM bitnami/wordpress:5.2.1-debian-9-r29

RUN sed -i 's/^upload_max_filesize\s*=.*/upload_max_filesize=512M/' /opt/bitnami/php/etc/php.ini
```

Alternatively you could replace the entire `php.ini` file here, by adding the line below:

```
COPY ./my_custom_php.ini /opt/bitnami/php/conf/php.ini
```

Currently the WordPress chart doesn't support mounting this file during the deployment, which is why it needs to be added via the Dockerfile. If this is a feature you think would be useful let us know.

Then change the Bitnami container used by the chart by changing `image.repository` and `image.tag` in the `values.yaml` of the chart (or by using `--set`).
