### ISSUE TITLE
Multiple FQDNs point to one container

### ISSUE THREAD

**Issue by stefangweichinger** [bitnami/bitnami-docker-wordpress#182]
Container wordpress runs on port 80 behind a HAproxy which does the SSL-Offloading.
https://www.mydomain1.com works 

2nd domain ... URL https://www.mydomain2.com should also point to the same site, and be forwarded to domain1 (use its cert etc)

I am unsure if I have to let Wordpress know something about the 2nd domain, and where to configure the forwarding: in HAproxy?

**Comment by miguelaeh** [comment]
Hi @stefangweichinger ,
I guess if you are using the `https://mydomain1.com` on Wordpress and the second one is forwarded to the first, the container needs to resolve the second domain to the first. So if it does not work automatically it could be due to the internal routes that Wordpress creates. So try to modify the `/etc/hosts` file of the container to resolve the second domain to the first one.
