### ISSUE TITLE
Error executing 'postInstallation': EPERM: operation not permitted, utime '/bitnami/wordpress/.restored'

### ISSUE THREAD

**Issue by aleksey005** [bitnami/bitnami-docker-wordpress#218]
**Description**

Wordpress not upgrade to chart 9.0.0 and not rollback to 8.1.6

**Steps to reproduce the issue:**

1. [First Step]
Upgrade from 8.1.6 to 9.0.0

**Describe the results you received:**

```
app-entrypoint.sh 07:54:13.81
app-entrypoint.sh 07:54:13.82 Welcome to the Bitnami wordpress container
app-entrypoint.sh 07:54:13.82 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress
app-entrypoint.sh 07:54:13.82 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress/issues
app-entrypoint.sh 07:54:13.82 Send us your feedback at containers@bitnami.com
app-entrypoint.sh 07:54:13.82
nami INFO Initializing apache
nami INFO apache successfully initialized
nami INFO Initializing php
nami INFO php successfully initialized
nami INFO Initializing mysql-client
nami INFO mysql-client successfully initialized
nami INFO Initializing wordpress
wordpre INFO ==> Preparing Varnish environment
wordpre DEBUG Deleting the Varnish example configuration file
wordpre INFO ==> Preparing Apache environment
wordpre DEBUG Creating the Apache configuration vhost file
wordpre DEBUG Creating the Apache configuration https vhost file
wordpre INFO ==> Preparing PHP environment
wordpre INFO WordPress has been already initialized, restoring...
wordpre TRACE [restorePersistedData] Restoring /bitnami/wordpress/wp-content to /opt/bitnami/wordpress/wp-content
wordpre TRACE [restorePersistedData] Restoring /bitnami/wordpress/wp-config.php to /opt/bitnami/wordpress/wp-config.php
Error executing 'postInstallation': EPERM: operation not permitted, utime '/bitnami/wordpress/.restored'
nami TRACE Error: Error executing 'postInstallation': EPERM: operation not permitted, utime '/bitnami/wordpress/.restored'
at Object.fs.utimesSync (fs.js:1222:11)
at setAttrs (/opt/bitnami/nami/node_modules/nami-utils/lib/file/set-attrs.js:23:8)
at Object.touch (/opt/bitnami/nami/node_modules/nami-utils/lib/file/touch.js:20:3)
at Object.wrappedFn (/opt/bitnami/nami/node_modules/nami-utils/lib/function-wrapping.js:191:17)
at Object.markAsRestored (/.nami/components/com.bitnami.wordpress/lib/volume.js:92:11)
at Object.restorePersistedData (/.nami/components/com.bitnami.wordpress/lib/volume.js:180:10)
at Component.$app.postInstallation (/.nami/components/com.bitnami.wordpress/main.js:80:21)
at Component.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)
at _.each.step (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:32)
at r (/opt/bitnami/nami/node_modules/lodash/index.js:5:348)
```

**Additional information you deem important (e.g. issue happens only occasionally):**

Rancher 2.3.5

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.1
 Git commit:        2d0083d
 Built:             Fri Aug 16 14:20:06 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.1
  Git commit:       2d0083d
  Built:            Wed Aug 14 19:41:23 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

- Output of `docker info`:

```
Containers: 94
 Running: 87
 Paused: 0
 Stopped: 7
Images: 106
Server Version: 18.09.7
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 
runc version: N/A
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-88-generic
Operating System: Ubuntu 18.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 11.72GiB
Name: ubuntu
ID: U652:V44V:NJ77:4YX3:UWFT:LZI4:4BG5:PZI5:2IKL:BAJT:BQ46:QLM4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```
not use
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
bare metall cluster

**Comment by Kubilai12** [comment]
Same for me many probleme since yesterday

**Comment by beltran-rubo** [comment]
This could be related to the changes specified at https://github.com/bitnami/bitnami-docker-wordpress#532-debian-10-r30 You can try to specify "USER root" in the docker-compose.yaml to continue using the same approach than before.

**Comment by secoldPrivate** [comment]
Just happened to me as well. Hope it's fixed soon.

**Comment by beltran-rubo** [comment]
This was a major change in the container and in the Chart in order to follow the best security practices for K8s deployments: use non-root images. https://github.com/bitnami/bitnami-docker-wordpress#532-debian-10-r30

It is a major version because it is difficult to maintain the compatibility and the upgrade features. There are recommendation to do a full migration using VaultPress or All-In-One Migration plugins to a totally new installation. Could you please try that migration?

**Comment by aleksey005** [comment]
Migration could be done if the sites worked))), but they no longer work and now you need to worry about how to restore them and this is a definite problem for those who have big ones and contain a lot of settings and content.

**Comment by Kubilai12** [comment]
I had a backup but when i want to rebuild fresh install i have other way with bug on wordpress starting ...
I decide to change image with official wordpress and it s ok

**Comment by juan131** [comment]
Hi everyone

As you can see at https://github.com/helm/charts/pull/21099 and https://github.com/helm/charts/issues/21098 WordPress has been moved to **non-root** and **existing data from previous versions is not compatible anymore.**

As can see in the README (see the link below), you'll need to migrate your data in order to upgrade to the latest version:

- https://github.com/helm/charts/tree/master/stable/wordpress#to-900

Upgrading from `8.x.x` to `9.x.x` is not possible using `helm upgrade ...` or equivalent commands.

Please note that, in order to migrate your site, you need to install a new WordPress chart and, once it's up and running, follow the migration guidelines. These migration guidelines will be different depending on the plugin you're using to migrate the site. 

Some popular plugins to do these operations are VaultPress or All-in-One WP Migration. Please note that not every plugin is valid to migrate your site. Some of them require a FTP server (which this image doesn't contain) or some others are not valid for big sites. Please find the one that fits your needs at:

- https://wordpress.org/plugins/

**Comment by ceejoyce** [comment]
I'm getting same problem on a new install on AKS 1.15.7 using AzureFiles for persistent storage.

Chart Version: 9.0.1
Image: 5.3.2-debian-10-r32

    Error executing 'postInstallation': EPERM: operation not permitted, utime /bitnami/wordpress/.restored'
    nami    TRACE Error: Error executing 'postInstallation': EPERM: operation not permitted, utime /bitnami/wordpress/.restored'

**Comment by ceejoyce** [comment]
For info: Looks like updating the AzureFiles mount options and adding uid=1001 and gid=1001 fixes it...

**Comment by juan131** [comment]
Hi @ceejoyce 

As you mentioned, the volumes you mount on WP containers should have gid=1001. That's the reason why the chart uses a SecurityContext to adapt them by default. See 

- https://github.com/helm/charts/blob/master/stable/wordpress/values.yaml#L187

**Comment by Pliind** [comment]
I've tried to set -u root, if done so i get "Error executing 'postInstallation': User '99' not found" 
Any help appreciated!

**Comment by Pliind** [comment]
now i renamed the .restore file, restarted. log shows all is well except for this..
Wordpress does not start and a new .restore file was created. 

`nami INFO wordpress successfully initialized
[0m[38;5;2mINFO [0m ==> Starting gosu...`

**Comment by juan131** [comment]
Hi @Pliind 

After running the container as root and renaming the `.restore` file, it should have started. Could you share the logs you obtain in the container?

**Comment by Pliind** [comment]
no it just gets stuck on "starting gosu..." and the container keeps on running but wordpress is not accessible. I've since this given up and went to online-hosting instead as the wordpress is among other a RVSP for my wedding.

**Comment by juan131** [comment]
Hi @Pliind 

I'm glad that you could find an alternative on online-hosting services.

**Comment by bartagabor** [comment]
> no it just gets stuck on "starting gosu..." and the container keeps on running but wordpress is not accessible. I've since this given up and went to online-hosting instead as the wordpress is among other a RVSP for my wedding.

Hi, we also investigated this issue for some hours. It does not stuck, it is running, but on port 8080. If you bind that port, instead of 80 (which worked previously), it will be fine.

**Comment by juan131** [comment]
Yes @bartagabor 

As it's explained at [Notable Changes section](https://github.com/bitnami/bitnami-docker-wordpress#notable-changes) the consequences of moving the container to a "non-root" approach include that one:

- The HTTP/HTTPS ports exposed by the container are now `8080/8443` instead of `80/443`.

**Comment by akhfa** [comment]
This is what I do

Edit deployment file replica with 0 
Mount the persistent volume manually
chown `1001:1001` `wp-content` directory and these files
```
-rw-rw----. 1 1000 1001    0 Nov 10 19:14 .htaccess
-rw-rw-r--. 1 root 1001    0 Nov  9 23:00 .initialized
-rw-rw-r--. 1 root 1001    0 Mar 25 19:55 .restored
```
Unmount the persistent volume manually
Revert deployment's replica value as before

I think broken changes like this should be documented how to fix manually, and I think something like this can be automated by sidecar container running chown when the pod is starting up 🤔

**Comment by juan131** [comment]
Hi @akhfa 

> I think broken changes like this should be documented how to fix manually

Under the Notable Changes section, we include the instructions to upgrade from previous versions of the image to the latest one, see https://github.com/bitnami/bitnami-docker-wordpress#notable-changes

We also included a section in the associated Helm chart warning users about the consequences of upgrading and the steps to follow, see https://github.com/bitnami/charts/tree/master/bitnami/wordpress#upgrading

> I think something like this can be automated by sidecar container running chown when the pod is starting up

We tried to avoid this kind of "hacky" solutions since they're likely to screw up permissions, even more with solutions like WP where each user installs different plugins and the permissions can be very different across different installations. That's why we recommended migrating the site using one of the existing solutions for WordPress.

That, said, the WP helm chart includes a parameter `sidecars` (see https://github.com/bitnami/charts/tree/master/bitnami/wordpress#sidecars) that allows everyone to add any sidecar container. So it's possible to add your custom solution to adapt the permissions.
