### ISSUE TITLE
Volume all files

### ISSUE THREAD

**Issue by Luancarlos** [bitnami/bitnami-docker-wordpress#229]
The volume is currently made up of the wp-content folder and the wp-config.php file
how to do so that the volume is made of all wordpress files

**Comment by juan131** [comment]
Hi @Luancarlos 

Why do you want to persist all the WP files? That will break the possibility to upgrade WordPress by replacing the image with a new version as it's explained in the link below:

- https://github.com/bitnami/bitnami-docker-wordpress#upgrading-wordpress

We're currently persisting `wp-content` and `wp-config.php` since all the WordPress data is saved on these directories (or the MySQL/MariaDB database). The rest of files are just PHP code and, by not persisting them, we can replace the "old" code whenever there's a new version of WordPress by simply replacing the image.

**Comment by Luancarlos** [comment]
how should i do if i need to execute the project without a docker?

**Comment by juan131** [comment]
This repository contains the Bitnami Docker image for WordPress. If you're looking for a WP solution on a different format, please note that we also offer Cloud images, VMs (to be used on VMware or VBox) and native installers. You can find more information at https://bitnami.com/stack/wordpress
