### ISSUE TITLE
Allow different HTTP_HOST in wp-cli

### ISSUE THREAD

**Issue by v-six** [bitnami/bitnami-docker-wordpress#236]
**Description**

In default `wp-config.php`, there is a block that is setting `$_SERVER["HTTP_HOST"]` to `127.0.0.1`. `WP_SITEURL` and `WP_HOME` are set using this variable.

Some plugins (cache plugins for example) need to have the correct `WP_SITEURL` and `WP_HOME` in order to work fully. 

**Describe the results you expected:**

I expect to have an environment variable to set this `HTTP_HOST` for the wp-cli.

**Additional information you deem important (e.g. issue happens only occasionally):**

Also tried to use the `--url` flag for wp-cli, without success.

**Comment by juan131** [comment]
Hi @v-six 

There's no environment variable to configure that at this moment. That said, as you can check in the script below, you can mount any custom script you want at `/docker-entrypoint-init.d` and it'll be execute during the 1st boot of the WordPress container:

- https://github.com/bitnami/bitnami-docker-wordpress/blob/master/5/debian-10/rootfs/post-init.sh

Using this, you can include a script that use `wp-cli` or a custom regex to adapt the `wp-config.php` automatically to your needs.

There's also an environment variable (`WORDPRESS_EXTRA_WP_CONFIG_CONTENT`) that allows to append any custom piece of code you want to add to the `wp-config.php` file. Please note this environment variable only works for **appending** but not for modifying the default config file.

**Comment by v-six** [comment]
I'm ok for the `/docker-entrypoint-init.d` but why stick this value in `wp-config.php` ? 
Setting `url` value in `.wp-cli/config.yml` isn't a best way to do the same thing ? It would allow modification with the wp-cli `--url` parameter.

**Comment by v-six** [comment]
Hi @juan131,

I realise that I was not clear in my issue explanation.

As you know, a lot of plugins are using `WP_SITEURL` and `WP_HOME` and need to have a proper value to work. Everything is fine from a browser with this container default `wp-config.php`. But when I try to use `wp-cli` with some plugins, the `127.0.0.1` value is a real problem.

Hard setting this `header` in `wp-config.php` forces us to replace the value using a bash script in `/docker-entrypoint-init.d`. To modify a simple value, I think this is needlessly complex.

Setting the `url` variable in `.wp-cli/config.yml` may be a better solution, cause it does exactly the same thing but has the advantage to be editable just by using the `--url=` parameter of `wp-cli`.

**Comment by juan131** [comment]
Hi @v-six 

I understand your concerns, thanks for the detailed explanation. Please note that we are configuring WordPress in a way that allow us to run it and serve the content through an unpredictable URL (or IP).

This container is designed to run on Kubernetes, using the [Bitnami WordPress Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/wordpress). Kubernetes is an environment where it's very likely that you don't know the URL or IP that'll be associated to the service exposing your WordPress website, since it's dynamically assigned by the cluster.

We know there are plugins that aren't compatible with that, and that's why we provide mechanisms to automatically adapt the default `wp-config.php` to their needs. The same way, we know there are plugins that require modifying some `.htaccess` files and we do not support them by default (see https://github.com/bitnami/bitnami-docker-wordpress#503-r20)

**Comment by v-six** [comment]
Hi @juan131,

I'm using your helm chart in order to deploy many Wordpress. I do understand all of your concerns, but what I am proposing here is to remove an hardcoded header and use a more "appropriate" way to set `127.0.0.1` as a default value allowing user modification.

As you mention, `.htaccess` files are not supported by default but it can be just by disabling an ENV var. It's a simple way to get a standard Wordpress behavior unlike running a script to remove a line in `wp-config.php`.

Anyway your right, this mechanisms to automatically adapt the default `wp-config.php` fit my needs. I'm just proposing an alternative :relaxed:

**Comment by juan131** [comment]
Hi @v-six 

Thanks for the feedback, we really appreciate it!!

We need to find a balance between allowing users customizing the WP configuration to their needs in an easy way (e.g. using environment variables) and supporting every single scenario, since the amount of env. vars, combinations, etc. to support and test will become very hard to maintain.

I mean, we can provide environment variables to setup "basic features" but users who want to go a step further should explore the alternatives we provide to [extend the image](https://github.com/bitnami/bitnami-docker-wordpress#extend-this-image) or mounting their custom scripts.

What do you think @javsalgar ?

**Comment by adnoh** [comment]
Hi all, I also have a problem with this setup. It makes it nearly impossible to use wp-cli in a multisite setup.
When hardcode the $_SERVER["HTTP_HOST"] to 127.0.0.1 you can't use wp cli with the --url= parameter. 
In my setup I use a custom script which converts my site to multisite at first boot, creates a new site and tries to tune it - I always get `Error: Site '127.0.0.1/' not found. Verify `--url=<url>` matches an existing site`

when I comment out the section in wp-config.php wp cli works fine, but I can't use it to bootstrap my environment
