### ISSUE TITLE
Including MariaDB in Docker Wordpress

### ISSUE THREAD

**Issue by GuyMight44** [bitnami/bitnami-docker-wordpress#237]
Hi, its not really a bug but a suggestion.

I understand I have to spin up another container to run MariaDB but I was wondering, could I run MariaDB & WordPress in the same container?

I tried making a simple Dockerfile like this:
```
FROM bitnami/mariadb:latest

ENV ALLOW_EMPTY_PASSWORD=yes

FROM bitnami/wordpress:latest

ENV ALLOW_EMPTY_PASSWORD=yes
ENV WORDPRESS_DATABASE_USER=root
ENV WORDPRESS_DATABASE_NAME=bitnami_wordpress
```

and it builds but when running, we end up with the same problem as before, where it gets stuck here:
```
nami    INFO  Initializing apache
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing wordpress
wordpre INFO  ==> Preparing Varnish environment
wordpre INFO  ==> Preparing Apache environment
wordpre INFO  ==> Preparing PHP environment
mysql-c INFO  Trying to connect to MySQL server
```
but then fails after 36 tries.

I was hoping to maybe launch WordPress in one container and then modify it to only keep the Apache, PHP, and MariaDB (all under non-root) without WordPress

Im not sure if its a WordPress issue or a MariaDB issue but I am referring to the MariaDB made by Bitnami.

**Comment by juan131** [comment]
Hi @GuyMight44 

Shipping both the web application and the database in the same container doesn't really make much sense.

When we think on VMs or monolithic solutions, it makes sense to think on solutions that ship everything you need to run your service. For instance, if you try one of the [Bitnami WordPress Native installers](https://bitnami.com/stack/wordpress/installer) or [Bitnami WordPress VMs](https://bitnami.com/stack/wordpress/virtual-machine), you'll find that both Apache, PHP, WordPress, MariaDB, and other secondary services such as Memcached are shipped under the same solution.

However, when we are in a container environment, we need to think on micro services. One of the greatest advantages on using containers is to divide our solutions on different components so we can:

- Isolate problems: when something is wrong in MariaDB container, it's because sth is wrong in MariaDB. There are no other service that might be affecting it.
- Scale each component separately: It might make sense to have 5/6 WordPress replicas (since we have too many web requests) but just a couple of MariaDB replicas (because there are very few database connections).

If you take a look to the [Twelve-Factor App document](https://12factor.net) that describe several principle to follow when designing applications for modern environments or [Docker documentation](https://docs.docker.com/config/containers/multi-service_container), you'll find that this is a generic recommendation in containers:

> It is generally recommended that you separate areas of concern by using one service per container

**Comment by GuyMight44** [comment]
Hi, i totally understand this and from a production view, this would make a lot of sense but for the sake of my local development and the ability to contain everything & the kitchen sink into one container, would it be possible to run a non-rooted docker container that has MariaDB, PHP, and Apache into one?

**Comment by juan131** [comment]
Hi @GuyMight44 

It also makes sense for your local deployment, you just need to use `docker-compose` to orchestrate:

```console
$ curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-wordpress/master/docker-compose.yml > docker-compose.yml
$ docker-compose up -d
```

Using [docker-compose](https://docs.docker.com/compose/) you don't need to worry about manually creating the containers, you can simply use `docker-compose up/down/restart` to create/delete/restart the containers.

> would it be possible to run a non-rooted docker container that has MariaDB, PHP, and Apache into one?

Yes, it's possible but you'll have to build your own container based on WP/MariaDB ones. As I said I highly advise against doing so, but it's technically possible.

**Comment by GuyMight44** [comment]
Hi @juan131 sorry for the long absense. I am willing to do that & i would move this discussion over to the MariaDB respitory because of this question: Lets say i would create a new container containing mariaDB & Wordpress. I have been trying to make them work but i am not sure what startup scripts/etc does MariaDB & wordpress need since they both share the same file names with different variations. If i were to copy specific files from MariaDB to the Wordpress container, which ones would I need for a rootless container?

> Yes, it's possible but you'll have to build your own container based on WP/MariaDB ones. As I said I highly advise against doing so, but it's technically possible.

I completely understand why and get what your saying, there is a good personal reason for it though & development needs this
