### ISSUE TITLE
Error executing 'postInstallation': EACCES: permission denied

### ISSUE THREAD

**Issue by darrenbarklie** [bitnami/bitnami-docker-wordpress#239]
**Description**

I am attempting to follow the Bitnami guide by @raquel-campuzano to [Deploy Locally Custom WordPress](https://docs.bitnami.com/tutorials/deploy-locally-custom-wordpress/).

**Steps to reproduce the issue:**

1. Follow the guide
2. Build custom image
3. `docker-compose up` new image

**Describe the results you received:**

Build is almost completed, but then hangs with:
```
wordpress_1  | mysql-c INFO  MySQL server listening and working at mariadb:3306
wordpress_1  | wordpre INFO  Preparing WordPress environment
wordpress_1  | Error executing 'postInstallation': EACCES: permission denied, rename '/opt/bitnami/wordpress/wp-content/plugins/bbpress/bbpress.php' -> '/bitnami/wordpress/wp-content/plugins/bbpress/bbpress.php'
```

When I attempt with another plugin, the same issue occurs:
```
Error executing 'postInstallation': EACCES: permission denied, rename '/opt/bitnami/wordpress/wp-content/plugins/advanced-custom-fields/acf.php' -> '/bitnami/wordpress/wp-content/plugins/advanced-custom-fields/acf.php'
```
I've noted that the downloaded and unzipped assets lack the __group write__ permission.  When I manually __chmod 775__ the folder/file mentioned in the error, the result is non-blocking, however sticks on the next file requiring renaming.  It seems heavy-handed to apply this recursively to every plugin/theme directory file, so thought to raise the issue.

I also note that the guide is using __5/debian-9/__, so is this a side effect on the new non-root containers?

Thanks in advance for the support.

**Comment by carrodher** [comment]
Hi, thanks for letting us know and reporting this issue.

You're right, the guide was not updated reflecting the latest changes in the WordPress container. I am creating an internal task to update the guide; in the meantime, can you apply the following changes?

- Create the `5/debian-10/rootfs/download-extra.sh` script
```bash
 #!/bin/bash

curl -o /tmp/bbpress.2.6.4.zip https://downloads.wordpress.org/plugin/bbpress.2.6.4.zip
curl -o /tmp/gambit.1.6.5.zip https://downloads.wordpress.org/theme/gambit.1.6.5.zip
unzip /tmp/bbpress.2.6.4.zip -d /opt/bitnami/wordpress/wp-content/plugins
unzip /tmp/gambit.1.6.5.zip -d /opt/bitnami/wordpress/wp-content/themes
```

- Activate the plugin and the them during initialization in `5/debian-10/rootfs/app-entrypoint.sh`:
```diff
    . /apache-init.sh
    . /wordpress-init.sh
    nami_initialize apache php mysql-client wordpress
+   su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate bbpress'
+   su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp theme activate gambit'
    info "Starting gosu... "
    . /post-init.sh
fi
```

- In the `5/debian-10/Dockerfile` you need to execute the script and also remove the `USER` directive in order to not run the container as user `1001`:
```diff
COPY rootfs /
+RUN bash download-extra.sh
ENV ALLOW_EMPTY_PASSWORD="no" \
    APACHE_ENABLE_CUSTOM_PORTS="no" \
    APACHE_HTTPS_PORT_NUMBER="8443" \
...
EXPOSE 8080 8443

-USER 1001
ENTRYPOINT [ "/app-entrypoint.sh" ]
CMD [ "httpd", "-f", "/opt/bitnami/apache/conf/httpd.conf", "-DFOREGROUND" ]
```

- Then you can build the image and use it in the `docker-compose` or you can directly edit the `5/debian-10/docker-compose.yaml` changing the `image` field by `build`, on this way the image is built when deploying the `docker-compose`:
```diff
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
-   image: 'bitnami/wordpress:5'
+   build: .
    ports:
      - '80:8080'
      - '443:8443'
```

- Running `docker-compose up` with the above changes, WP should be successfully initialized and the plugin/theme activated:
```
wordpress_1  | nami    INFO  wordpress successfully initialized
wordpress_1  | Plugin 'bbpress' activated.
wordpress_1  | Success: Activated 1 of 1 plugins.
wordpress_1  | Success: Switched to 'Gambit' theme.
```
Please, note that I am doing all the changes in `5/debian-10`, not in the `docker-compose.yaml` hosted at the root of the directory.

Are you able to solve the issue following this approach? I am going to update the guide reflecting those changes.

**Comment by darrenbarklie** [comment]
Thanks very much @carrodher, will try this shortly and report back.

**Comment by darrenbarklie** [comment]
Thanks very much @carrodher, I can confirm that removing `USER: 1001` resolves my issue.  Really appreciate the support.

**Comment by carrodher** [comment]
Thanks for letting us know, we are also working on improving the guide with this and other changes (install `unzip` is not needed anymore, `debian-9` removal, etc).

Please, don't hesitate to reopen the issue if something doesn't work as expected.
