### ISSUE TITLE
Fresh bitnami/wordpress:5.4.2 throws PHP errors.

### ISSUE THREAD

**Issue by benhus** [bitnami/bitnami-docker-wordpress#254]
**Description**

The bitnami/wordpress:5.4.2 throws PHP exception on various occasions. E.g. Installing Templates, Plugins etc. The simplest way to reproduce it though is just to hit the re-installation. 

**Steps to reproduce the issue:**

1. Start fresh bitnami/wordpress:5.4.
2. Log into the admin console
3. Navigate to Home/Updates
4. Click "Reinstall Now" Button

**Describe the results you received:**

The output is as follows: 

```
Downloading update from https://downloads.wordpress.org/release/wordpress-5.4.2-no-content.zip…

The authenticity of wordpress-5.4.2-no-content.zip could not be verified as no signature was found.

Unpacking the update…


Warning: chmod(): Operation not permitted in /opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 168
Verifying the unpacked files…

Preparing to install the latest version…

Enabling Maintenance mode…

Copying the required files…


Notice: Trying to access array offset on value of type bool in /opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 226 (This is repeated 100+ times)

Warning: chmod(): Operation not permitted in /opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 168

Warning: chmod(): Operation not permitted in /opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 168

Warning: chmod(): Operation not permitted in /opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 168
Disabling Maintenance mode…

Upgrading database…
```

**Describe the results you expected:**

No Errors should occur

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:21:05 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:19:41 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 19
  Running: 17
  Paused: 0
  Stopped: 2
 Images: 185
 Server Version: 19.03.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-51-generic
 Operating System: Ubuntu 18.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 62.82GiB
 Name: tqg-prod-01
 ID: WH3R:7FGE:EZ5Y:APEQ:IIEL:B4UT:4ZXC:4G2S:EXQL:3BFG:HX7S:VPAH
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  tqg-dev:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.17
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by benhus** [comment]
Hi,

it seems as there is a problem with wordpress and PHP 7.4. Could you create an image/tag with PHP 7.3?

Thank you in advance

Kind regards,
Benjamin

**Comment by marcosbc** [comment]
Hi @benhus, AFAIK WordPress is fully compatible with PHP 7.4. If you find issues installing themes, plugins, etc., it's more likely to be related to those plugins not being ready for 7.4 rather than WordPress itself.

If you think that is not the case, could you clarify the specific errors you find?

As for your re-installation issue, I tested it locally in a container and the process went fine, no errors, using 5.4.2. Not sure why you are finding those issues. Are you sure you're using 5.4.2 and not [5.3.2 which included major changes](https://github.com/bitnami/bitnami-docker-wordpress#532-debian-10-r30)?

**Comment by benhus** [comment]
Hi @marcosbc,

you need to enable the debugging mode. Edit the "wp-config.php" and set define( 'WP_DEBUG', true );

I have tried the same with the image PHP 7.4. and had these errors and with 7.3. no errors occurred. 

Would be great if you could check that.

thank you very much for taking your time to have a look into this.

Kind regards,
Benjamin

**Comment by benhus** [comment]
Hi @marcosbc,

is there any update?

Kind regards,
Benjamin

**Comment by benhus** [comment]
Hi @marcosbc,

can you give me here some assistance. I have 5 sites running with older versions of the bitnami containers (before moving from root to none root) and they all had never issues. And now I can not install a simple theme on this wordpress container. Everything is bugged. 

Thank you in advance
Kind regards,
Benjamin

**Comment by marcosbc** [comment]
@benhus After looking into this, I could not see any major issue apart from a few warnings being printed out when upgrading WordPress:

```
...
wordpress_1  | [Thu Jul 09 17:27:23.161848 2020] [php7:warn] [pid 55] [client 192.168.160.1:46492] PHP Warning:  chmod(): Operation not permitted in /opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 168, referer: http://localhost:8080/wp-admin/update-core.php
...
wordpress_1  | [Thu Jul 09 17:27:39.627297 2020] [php7:notice] [pid 42] [client 192.168.160.1:47040] PHP Notice:  Trying to access array offset on value of type bool in /opt/bitnami/wordpress/wp-admin/includes/class-wp-filesystem-direct.php on line 226, referer: http://localhost:8080/wp-admin/theme-install.php?browse=featured
...
```

Those warnings/notices appear in the Apache error log and in the website (although they disappear after the page reloads).
And I would not worry over those warnings/notices, since they are only referring to some file system actions (which obviously are not completed since the container running as a non-root user).

NOTE: You should not be clicking on "re-install" or "upgrade" the WordPress container, since it would be reverted once the container is re-created. The proper way to upgrade WordPress is to change the container image tag.

>And now I can not install a simple theme on this wordpress container. Everything is bugged.

I could install themes without seeing any warnings. Could you describe the steps you're following? I just installed it via the WP Admin panel.

_____

In order not to block you, below I'm going to describe a workaround so you can run PHP 7.3 with WordPress.

To do that, you will have to fork the [container repository](https://github.com/bitnami/bitnami-docker-wordpress) and edit the `Dockerfile` in the `5/debian-10` directory:

```diff
diff --git a/5/debian-10/Dockerfile b/5/debian-10/Dockerfile
index 10f9bc2..4145355 100644
--- a/5/debian-10/Dockerfile
+++ b/5/debian-10/Dockerfile
@@ -10,11 +10,11 @@ COPY prebuildfs /
 RUN install_packages ca-certificates curl gzip libaudit1 libbsd0 libbz2-1.0 libc6 libcap-ng0 libcom-err2 libcurl4 libexpat1 libffi6 libfftw3-double3 libfontconfig1 libfreetype6 libgcc1 libgcrypt20 libglib2.0-0 libgmp10 libgnutls30 libgomp1 libgpg-error0 libgssapi-krb5-2 libhogweed4 libicu63 libidn2-0 libjemalloc2 libjpeg62-turbo libk5crypto3 libkeyutils1 libkrb5-3 libkrb5support0 liblcms2-2 libldap-2.4-2 liblqr-1-0 libltdl7 liblzma5 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libmcrypt4 libmemcached11 libmemcachedutil2 libncurses6 libnettle6 libnghttp2-14 libonig5 libp11-kit0 libpam0g libpcre3 libpng16-16 libpq5 libpsl5 libreadline7 librtmp1 libsasl2-2 libsqlite3-0 libssh2-1 libssl1.1 libstdc++6 libsybdb5 libtasn1-6 libtidy5deb1 libtinfo6 libunistring2 libuuid1 libx11-6 libxau6 libxcb1 libxdmcp6 libxext6 libxml2 libxslt1.1 libzip4 procps sudo tar unzip zlib1g
 RUN /build/bitnami-user.sh
 RUN /build/install-nami.sh
-RUN bitnami-pkg install php-7.4.7-3 --checksum a3cc4085af40408be5bb2c7cf1aab43497ff3f49c1404aea84ece63a2f822510
+RUN bitnami-pkg install php-7.3.19-2 --checksum 25bba77655b298c62ab474954837acbc167a4bcc8555c39b419644c999207c5f
 RUN bitnami-pkg unpack apache-2.4.43-5 --checksum e9faded57e3703fe9fcea650eb302e673d969a399fe9dfafa67e173465637665
 RUN bitnami-pkg install wp-cli-2.4.0-0 --checksum 8095bdd2f96a137cb3f54836ad9deb90510b0927472e532f41e1708345432230
 RUN bitnami-pkg unpack mysql-client-10.3.23-1 --checksum efab843077267af6a8cde53440a1fef0acf8cb67ab1dcd0b6da2e9cbe050c7e1
-RUN bitnami-pkg install libphp-7.4.7-2 --checksum e57c8433c7cbe83ceea34c438aaaec271621b8032636418a18daf4d6799c64e2
+RUN bitnami-pkg install libphp-7.3.19-2 --checksum c5dddf3ea541f5c0d6f65fa7d743de710de5ec53cdf8458a25c74e70f0c8397d
 RUN bitnami-pkg unpack wordpress-5.4.2-7 --checksum 95c0ddcd4ae871df684399c7d0ba091269adc8fadf2317a14b92a7f9fd7a1d9f
 RUN bitnami-pkg install tini-0.19.0-0 --checksum 9a8ae20be31a518f042fcec359f2cf35bfdb4e2a56f2fa8ff9ef2ecaf45da80c
 RUN bitnami-pkg install gosu-1.12.0-1 --checksum 51cfb1b7fd7b05b8abd1df0278c698103a9b1a4964bdacd87ca1d5c01631d59c
```

**Comment by benhus** [comment]
Hi @marcosbc,

Thank you for your reply. I have tried the setup with php 7.3. but it seem to still have similar issues. So now back to the latest bitnami/worpress. I have a NGINX container as a load-balancer in front and your WordPress in the back. Below is the full setup I have. I have tried these teams on a WordPress hoster and all of them are running fine. Same config at the hoster, php 7.4 latest WordPress.
 

The relevant config of the nging default.config:

```
server {
        server_name www.mydomain.com;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        return 301 https://$host$request_uri;
}
server {
        server_name www.mydomain.com;
        listen 443 ssl http2 ;
        access_log /var/log/nginx/access.log vhost;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
        ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:!DSS';
        ssl_prefer_server_ciphers on;
        ssl_session_timeout 5m;
        ssl_session_cache shared:SSL:50m;
        ssl_session_tickets off;
        ssl_certificate /etc/nginx/certs/www.mydomain.com.crt;
        ssl_certificate_key /etc/nginx/certs/www.mydomain.com.key;
        ssl_dhparam /etc/nginx/certs/www.mydomain.com.dhparam.pem;
        ssl_stapling on;
        ssl_stapling_verify on;
        ssl_trusted_certificate /etc/nginx/certs/www.mydomain.com.chain.pem;
        add_header Strict-Transport-Security "max-age=31536000" always;
        include /etc/nginx/vhost.d/default;
        location / {
                proxy_pass http://www.mydomain.com;
                include /etc/nginx/vhost.d/www.mydomain.com_location;
        }
}
```

the vhost config:
```
        location / {
                proxy_http_version 1.1;
                proxy_redirect off;
                proxy_set_header Host $host:$server_port;
                proxy_pass https://wp-mydomain:8443;
                proxy_pass_request_headers      on;
                proxy_buffer_size          128k;
                proxy_buffers              4 256k;
                proxy_busy_buffers_size    256k;

        }
```

dockerfile:
```
FROM bitnami/wordpress
RUN sed -i -r 's/#LoadModule remoteip_module/LoadModule remoteip_module/' /opt/bitnami/apache/conf/httpd.conf
RUN echo "<IfModule remoteip_module>" >> /opt/bitnami/apache/conf/httpd.conf
RUN echo "  RemoteIPHeader X-Forwarded-For" >> /opt/bitnami/apache/conf/httpd.conf
RUN echo "  RemoteIPTrustedProxy 172.27.0.3" >> /opt/bitnami/apache/conf/httpd.conf
RUN echo "</IfModule>" >> /opt/bitnami/apache/conf/httpd.conf
RUN sed -i -r 's/max_execution_time = 30/max_execution_time = 600/' /opt/bitnami/php/conf/php.ini
RUN sed -i -r 's/;max_input_vars = 1000/max_input_vars = 3000/' /opt/bitnami/php/conf/php.ini
```
docker-compose.yml
```
version: '3.5'
services:
  mariadb:
    restart: always
    image: 'bitnami/mariadb:latest'
    container_name: wpdb-mydomain
    networks:
      - local
    volumes:
      - 'mariadb_data:/bitnami'
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - MARIADB_PASSWORD=bitnami_password
      - MARIADB_ROOT_PASSWORD=bitnami_password
  wordpress:
    restart: always
    build: .
    container_name: wp-mydomain
    networks:
      - local
      - backend
    volumes:
      - 'wordpress_data:/bitnami'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=wpdb-mydomain
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - WORDPRESS_DATABASE_PASSWORD=bitnami_password
      - WORDPRESS_USERNAME=admin
      - WORDPRESS_EMAIL=info@email.com
      - WORDPRESS_PASSWORD=bitnami_password
      - SMTP_HOST=smtp.mail.com
      - SMTP_PORT=587
      - SMTP_USER=wordpress@email.net
      - SMTP_PASSWORD=bitnami_password
      - SMTP_PROTOCOL=tls

networks:
  local:
    driver: bridge
  backend:
    external:
     name: backend

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
```

with this setup when installing a theme e.g. this free template here:

https://themeisle.com/themes/neve/

and there selecting any woo-commerce shop, always something is broken. E.g. a color style is missing etc. 

It is even more server with other templates which are more complex, e.g. this paid template here:
https://themeforest.net/item/porto-responsive-wordpress-ecommerce-theme/9207399

I hope this gives you a better idea of what is happening here.

Thanks again for your support and help.

Kind regards,
Benjamin

**Comment by marcosbc** [comment]
>with this setup when installing a theme e.g. this free template here:
>
>https://themeisle.com/themes/neve/


I installed the 'neve' theme and it worked without issues for me. No warnings, and WP_DEBUG is enabled.

However, I'm a bit confused by this:

>and there selecting any woo-commerce shop, always something is broken. E.g. a color style is missing etc.

Could you clarify what you mean?

>It is even more severe with other templates which are more complex, e.g. this paid template here:
>https://themeforest.net/item/porto-responsive-wordpress-ecommerce-theme/9207399
>
>With the porto theme just after importing it, you can't open the options page. It states "Sorry, you are not allowed to access this page." Which also occurs that it can not find the page. Here again, on the WordPress hoster works like a charm.

As for the paid theme, it could be possible due to not being compatible with a non-root environment. You could always try to set `user: 'root'` to make it be run by root. In any case, I would recommend to contact the theme authors.

**Comment by benhus** [comment]
@marcosbc 

to see something which is more obvious to reproduce, can you download the porto theme, install it and the go to the menu item "porto/theme options" and see if it works?

Here is the theme file: https://www.dropbox.com/s/5rbhmnyzou9n5ro/porto.zip?dl=0

I will try to run it as root to see if it makes a difference. 

As well I will try to see if the support of the theme is aware of non-root environments. 

Let me know if you could access the options. I always get the issue as mentioned : "Sorry, you are not allowed to access this page."

Thank you in advance
Kind regards,
Benjamin

**Comment by benhus** [comment]
@marcosbc 

I have tried to run it as root, same problem. You can't access the theme options. There seems to be some other glitch... 

Cheers,
Benjamin

**Comment by marcosbc** [comment]
@benhus I could install the theme without issues. I'm starting to think that your issues could be happening because of the NGINX proxy. The error `Sorry, you are not allowed to access this page.` could be happening because of a redirection.

Could you check if it is the case? To do that, run the following command:

```
curl -I http://www.mydomain.com
```

If you see something like this:
```
Location: http://www.myotherdomain.com/
```

Then it means a redirection is happening. And it could be possible the NGINX proxy has something to do with that.

If that is the case, then also when you access the WP URL without proxy, then it should not show that error. Could you verify this?

I'll continue to debug the configuration on my side as well, in case I find anything.

**Comment by benhus** [comment]
@marcosbc 
here are the results
```
curl -I http://www.helloworld.com does redirect to https://www.helloworld.com
HTTP/1.1 301 Moved Permanently
Server: nginx/1.14.1
Date: Mon, 13 Jul 2020 19:34:12 GMT
Content-Type: text/html
Content-Length: 185
Connection: keep-alive
Location: https://www.helloworld.com

```
```
curl -I https://www.helloworld.com
HTTP/2 301
server: nginx/1.14.1
date: Mon, 13 Jul 2020 19:34:23 GMT
content-type: text/html; charset=UTF-8
location: https://www.helloworld.com
x-powered-by: PHP/7.4.7
x-redirect-by: WordPress
strict-transport-security: max-age=31536000

```

here are the curls from the within nginx container to the bitnami/docker container. 

```
curl -I http://wp-helloworld:8080

HTTP/1.1 301 Moved Permanently
Date: Mon, 13 Jul 2020 19:44:58 GMT
Server: Apache/2.4.43 (Unix) OpenSSL/1.1.1d PHP/7.4.7
X-Powered-By: PHP/7.4.7
X-Redirect-By: WordPress
Location: http://wp-helloworld/
Content-Type: text/html; charset=UTF-8
```

```
curl -I -k https://wp-helloworld:8443

HTTP/1.1 301 Moved Permanently
Date: Mon, 13 Jul 2020 19:46:17 GMT
Server: Apache/2.4.43 (Unix) OpenSSL/1.1.1d PHP/7.4.7
X-Powered-By: PHP/7.4.7
X-Redirect-By: WordPress
Location: https://wp-helloworld/
Content-Type: text/html; charset=UTF-8
```

**Comment by benhus** [comment]
@marcosbc I have now exposed the container directly and removed the dockerfile changes. So I am running now the stock bitnami/wordpress and accessing it directly via https://1.2.3.4:8443. The I login into WordPress, delete all plugins and upload the theme. After that I get the same error. I am now really confused how we can have different behavior...

**Comment by benhus** [comment]
@marcosbc 

Just to added that the only change after starting up the container was to edit the wp-config.php and set

define('WP_SITEURL', ' https://1.2.3.4:8443/');
define('WP_HOME', ' https://1.2.3.4:8443/');

**Comment by marcosbc** [comment]
Hi @benhus, I could finally reproduce this issue. It is specific to the "Theme Options" page, so dismiss my previous comments on this being related to redirections.

After granting the web server access to the `/bitnami/wordpress` directory (by editing `/opt/bitnami/apache/conf/vhosts/wordpress-vhost.conf`) and reloading the web server configuration (`apachectl -k graceful`), I could see this error:

```
Deprecated: Array and string offset access syntax with curly braces is deprecated in /bitnami/wordpress/wp-content/themes/porto/inc/functions/general.php on line 178
```

I could also see the following content in some CSS files:

```
<b>Notice</b>:  Trying to access array offset on value of type null in <b>/bitnami/wordpress/wp-content/themes/porto/inc/admin/scssphp/src/Compiler.php</b> on line <b>5085</b><br />
```

However, I also deployed a Bitnami WordPress stack and there the page loads properly. I really have no idea why it is failing, it does look like a theme requirement not being satisfied. I would recommend to contact the plugin authors to investigate further.

For now, since it looks like the Porto theme don't work with the Bitnami WordPress container, I can only recommend to try the Bitnami WordPress stack where it's confirmed working, a non-Bitnami product or try another theme.

Note that the stock themes seem to work so I'm pretty convinced it does not have much to do with how WordPress is deploy, rather than limitations of the themes themselves.

**Comment by benhus** [comment]
@marcosbc  thank you for the update. 

Can you elaborate on what you mean by "I also deployed a Bitnami WordPress stack and there the page loads properly". I am a bit confused now where the "Theme Options" page is working. Because I thought we are working on the Bitnami WordPress stack. Just to understand better what you mean. 

Or did I misunderstand now, that it was working in some scenario?

Cheers,
Ben

**Comment by marcosbc** [comment]
Yes, sorry, I was referring to the [Bitnami WordPress stack](https://bitnami.com/stack/wordpress), which uses a different configuration than the Bitnami WordPress container image (this). I.e. it includes other plugins and configurations, and does not run inside a container.

**Comment by benhus** [comment]
@marcosbc, doesn't it make sense to have the same plugins and configurations running in the container?

**Comment by marcosbc** [comment]
In most cases, it would make sense to share the same list. We have an internal task to normalize the list of plugins between cloud images and container images soon but we haven't started working on it yet.

Note that the stack contains other things such as translations, PHP PECL extensions, etc. Also, since the initialization logic is different, some resulting files are different as well.

**Comment by benhus** [comment]
@marcosbc so it means, that the containers are not a reliable environment, and should not be used for production?

**Comment by marcosbc** [comment]
Note that containers by themselves are not ready for production, you need the infrastructure in place for it to be supported in production. That could be Kubernetes or a similar environment.

In this particular case, the issue we're seeing is happening only in containers, but we don't know the reason yet. This could be happening because the plugin is not supported in such environments, because of an issue in the plugins themselves, or because there is a misconfiguration in the container.

However, stock/official themes work without issues, same with plugins, so this looks like some WordPress internal issue with that specific theme on certain environments (these kind of issues happen sometimes). My advise is to check this with the theme/plugin author so they can investigate further, and beyond the WordPress 403 errors.
