### ISSUE TITLE
database name ENV var

### ISSUE THREAD

**Issue by andrewmclagan** [bitnami/bitnami-docker-wordpress#28]
Seems we are almost there with this image.

Although is there any chance of adding in a `MARIADB_NAME` to specify the actual name of the database?

**Comment by prydonius** [comment]
Sorry for the late response. Currently, we've assumed that the MariaDB container would only be used by the WordPress container, so there would be no conflicts. Would you be able to tell me a little bit more about your usecase?

**Comment by andrewmclagan** [comment]
Was intending on using this on a high traffic Laravel installation.

**Comment by prydonius** [comment]
I'm a little confused about how you're running this WordPress image. Are you using this for it's PHP and Apache components to run your Laravel app? If so, aren't you able to use whatever database name you choose? You can also configure the MariaDB image to create a database on initialisation: https://github.com/bitnami/bitnami-docker-mariadb#creating-a-database-user-on-first-run.

You might also be interested in the following tutorial on orchestrating a LAMP stack application using containers: https://github.com/bitnami/bitnami-docker/blob/master/tutorials/subrion.md.

**Comment by sahin** [comment]
We want to use our remote mysql database with this great docker container. 

It will be great if we can add MARIADB_NAME

**Comment by prydonius** [comment]
@sahin @andrewmclagan we are working on adding support for specifying an existing database for initialisation. We'll update this issue once a version including that support is released.

**Comment by sahin** [comment]
@prydonius exactly, the simpler explanation of the problem is using an existing database.

**Comment by sahin** [comment]
we are very eager to use this docker vs standard docker, do u any update for external mysql (existing or new)

**Comment by sahin** [comment]
@prydonius any updates?

**Comment by prydonius** [comment]
Hey @sahin, it's pretty high priority for us, however since this change will affect most of our applications and requires changes in our build/testing pipeline I can't currently give an estimation. I'll update this issue when we can become more certain about a release date.

Thanks and really sorry for the delay on this, hopefully you can find a workaround for this in the meantime.

**Comment by babyfooter** [comment]
Hi @prydonius, do you have some update about this enhancement, I'm really interest on it too. Thx a lot

**Comment by prydonius** [comment]
cc @juamedgod @jloramas

**Comment by sahin** [comment]
@juamedgod @jloramas any update?

**Comment by prydonius** [comment]
Hey @sahin @babyfooter, we are getting close to releasing a new version of the package to handle this, but are waiting on syncing the release with our VM-base offerings. Thanks for being patient on this, and I know it's taken some time but we are almost there!

**Comment by sahin** [comment]
@prydonius we are so excited to use this docker, and any updates? is it possible to have development version in a development branch

**Comment by grantpalin** [comment]
Also interested in this functionality so I can have a single database instance used by multiple applications.

**Comment by jotadrilo** [comment]
Hey @grantpalin @sahin @andrewmclagan @babyfooter, thanks for your patient on this.

It took more than expected since we were waiting on syncing this feature release with our VM-base offerings.

We have released [4.7.2-r2](https://github.com/bitnami/bitnami-docker-wordpress/releases/tag/4.7.2-r2) with this feature and also updated our documentation so you can connect to an existing database. As you will notice, we updated the default `docker-compose.yml` to take this into account. Now, it will rely on the [Bitnami MariaDB Docker Image](https://github.com/bitnami/bitnami-docker-mariadb) for creating the database so WordPress is initialized with an existing database by default. See [this section](https://github.com/bitnami/bitnami-docker-wordpress#connect-wordpress-docker-container-to-an-existing-database) for more information.

We hope this enhancement works for you.
