### ISSUE TITLE
docker-compose with persistance and mounted folder.

### ISSUE THREAD

**Issue by danielschlegel** [bitnami/bitnami-docker-wordpress#298]
**Description**

I try to find the right solution to have a docker-compose setup for local development.
The goal is to completely seperate wp-core from custom code and be able to change a file locally that should instantly available on reload in browser.

As the files are symlinked from /bitnami/wordpress to /opt/bitnami/wordpress i don't get how todo this.

My dockerfile looks similar like this.
```
FROM bitnami/wordpress:5.7.2
COPY my-wp-content /opt/bitnami/wordpress/wp-content
```

The problem is, that i cannot have a volume  my-wp-content:/opt/bitnami/wordpress/wp-content in docker-compose.yml since the changes in my-wp-content do get symlinked while initialize and changes do not have any effects. If i have a volume for /bitnami/wordpress i can change the files in there but i have to backport it to my-wp-content folders what is not a good solution in my opinion. Is there a proper solution for this?

**Comment by juan131** [comment]
Hi @danielschlegel 

As you mentioned this image is designed so the **wp-content** directory and **wp-config.php** configuration file are persisted (by mounting a volume at `/bitnami/wordpress`) while **the rest of the PHP code is not persisted** (under `/opt/bitnami/wordpress`). 

Why do we do this? Well, by doing this you can update WordPress by simply replacing the image with a new version without losing your data (which is persisted in the volume). For instance, you're running the `bitnami/wordpress:5.7.1` image and you can upgrade WordPress (plus other components such as Apache or PHP) by replacing the image with `bitnami/wordpress:5.7.1` image. Find more info about this process [in this link](https://github.com/bitnami/bitnami-docker-wordpress#upgrade-this-image). 

Going back to what you're trying to achieve, I have a question: do you want to customize the files under **wp-content** or do you also want to edit the rest of the PHP code?

If you just want to edit the **wp-content** directory, you can mount a directory from the host at `/bitnami/wordpress` as it's explained [here](https://github.com/bitnami/bitnami-docker-wordpress#mount-host-directories-as-data-volumes-with-docker-compose) (without modifying the original WordPress image, no Dockerfile is needed). Then, you launch the WordPress container, wait for it to be ready and start editing your WP site by modifying the content in the directory you mounted. In order to reload your changes, you can simply run `apachectl -k graceful` inside the WordPress container.

**Comment by danielschlegel** [comment]
Hi @juan131 
Thanks a lot for your answer and explanations. I have seen this docs but what i still don't get how i should handle the persistent volume while development. I want to be able to automatically setup branch based deployments. So if i want to spin up a completely new instance of my custom wp  i need to put my files also into /opt/bitnami or copy the persistent file to there manually(which i want to avoid) or am i wrong with this? I researched a lot but did not find any solution for this.

**Comment by juan131** [comment]
Hi @danielschlegel 

> So if i want to spin up a completely new instance of my custom WP I need to put my files also into /opt/bitnami or copy the persistent file to /bitnami/wordpress manually(which i want to avoid) or am i wrong with this?

If you customize your WP site following the approach I mentioned on my previous response, see:

> If you just want to edit the wp-content directory, you can mount a directory from the host at `/bitnami/wordpress` as it's explained here (without modifying the original WordPress image, no Dockerfile is needed). Then, you launch the WordPress container, wait for it to be ready and start editing your WP site by modifying the content in the directory you mounted. In order to reload your changes, you can simply run `apachectl -k graceful` inside the WordPress container.

Then, it's necessary that you backup the content of the volume you're mounting at `/bitnami/wordpress` to transfer your customizations to a new instance. In the new instance, you simply need to launch the container mounting an already populated volume with the data you backed up previously.

--- 

> basically i want to be able do docker-compose up without having any persistent data yet and get the fully customized wp.

To achieve that you don't haver other alternative rather than customizing the WordPress image.
