### ISSUE TITLE
Don't require authentication for SMTP

### ISSUE THREAD

**Issue by BenB196** [bitnami/bitnami-docker-wordpress#299]
**Description**

Currently it is not possible to setup SMTP without also setting up authentication. There are valid use-cases to not need authentication when using SMTP. (sending to a local SMTP server)

Currently: https://github.com/bitnami/bitnami-docker-wordpress/blob/fc0b6804d14e169aeeee8a027ea6b7549e327cd4/5/debian-10/rootfs/opt/bitnami/scripts/libwordpress.sh#L130 prevents SMTP from working without authentication. Ideally an additional variable of something like: ```SMTP_AUTH = true || false``` could be added so authentication could be toggle-able.

**Comment by juan131** [comment]
You're right @BenB196 

The line below also confirms that we're always forcing authentication for SMPT:

- https://github.com/bitnami/bitnami-docker-wordpress/blob/fc0b6804d14e169aeeee8a027ea6b7549e327cd4/5/debian-10/rootfs/opt/bitnami/scripts/libwordpress.sh#L324

I guess we could improve the logic to make it optional. @marcosbc do you see any cons on doing so?

**Comment by marcosbc** [comment]
Hi, thanks for reporting this! We are aware of this issue and are already working on a fix for this image and Discourse, amongst others.

**Comment by marcosbc** [comment]
Hi, this should have been fixed in [`5.7.2-debian-10-r20`](https://github.com/bitnami/bitnami-docker-wordpress/commit/570b7962243faede4d85b9e1e1bba6eafcbf8dc3). I'm going to close this issue, but please let us know if you continue finding problems with it.

**Comment by rjbaat** [comment]
Hi,  I am interested in this aswell. I use a local smtp relay with no auth on k8s. How can I make sure the wp-mail-smtp plugin is setup with no auth and no TLS required? The current helm chart doesn't provide the options for it atm if I am correct?

**Comment by rafariossaa** [comment]
Hi,
  Did you try with the `smtpXXXX` parameters ?

**Comment by rjbaat** [comment]
@rafariossaa Yes i did use those and left them empty since i dont want to use the smtp auth. Only host and port. I connect to a local postfix relay container (https://github.com/juanluisbaptiste/docker-postfix ) without the need and options to use username and password. 

The problem is the wp mail plugin gets installed with auth enabled and then giving a auth error on sending. When i manually set the auth to false in the plugin interface it does work. But not on start of the wp container 😔. Would be awesome if the plugin can be set to auth false from the start without the need to manually do this from the interface. 

I am using this toghether with the bitnami helm chart btw.

**Comment by rafariossaa** [comment]
Hi,
 Thanks for the explanation, I see.
 I am updating our internal task.
