### ISSUE TITLE
Not able to Install proc_open

### ISSUE THREAD

**Issue by himanshuahuja96** [bitnami/bitnami-docker-wordpress#300]
**Description**
I am trying to integrate Gitium a Git plugin and I needed Git Cli and proc_open to be enabled. I have successfully installed git in docker image but not able to install/enable the proc_open.

**Steps to reproduce the issue:**

1. apt-install proc_open
2. Unable to find module

**Describe the results you received:**
It was throwing error when I was building the container.

**Describe the results you expected:**
I was expecting it to install the proc_open and I can implement https://wordpress.org/plugins/gitium/

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:49:36 2021   
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021   
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 4
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.72-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 5.699GiB
 Name: docker-desktop
 ID: A5RF:2UXB:FGP7:L6Q6:HHWC:6NLV:FSPL:ORQT:YLXG:FAUR:JRJ5:6WA4
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.29.1, build c34c88b2
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Docker for Windows

I want to have a way to only mount plugin, themes, language not uploads. I will be using S3 Bucket for media files: Can you please suggest some solution for this one too?

Can you please help on these two points?

Thank you!

**Comment by migruiz4** [comment]
Hi @himanshuahuja96,

I haven't been able to reproduce your issue using the latest version of bitnami/wordpress.

The image already has PHP installed and does not require any additional changes to enable `proc_open`.

![image](https://user-images.githubusercontent.com/37381070/121483527-95e21600-c9ce-11eb-98b0-148393db9d31.png)

The steps I followed:

- Add the missing Gitium dependencies,`git` and `ssh`, using the following command:
```
install_packages git ssh
```
- Log into the Admin panel and go to 'Plugins' > 'Add New'. There, search for 'Gitium'.

- Install Gitium and activate it.

- Gitium should now appear on the sidebar, click on it and configure your repository.

**Comment by himanshuahuja96** [comment]
Hi @migruiz4 

Thanks for taking a look. I am deploying the image with the above suggested changes. I will update you on this.

And can you please help below point too?

I want to have a way to only mount plugin, themes, language expect uploads. I want to use S3 Bucket for media files/uploads. 

**Can you please suggest some solution for this one too?**

**Comment by migruiz4** [comment]
Hi @himanshuahuja96,

That issue is caused by running the container as non-root user (1001).
The SSH client requires user 1001 to exists in `/etc/passwd`, otherwise it will trigger the error `No user exists for uid 1001 fatal`

We have seen similar issues with other plugins caused by the same problem: https://github.com/bitnami/bitnami-docker-jenkins/issues/60#issuecomment-708305057

There are two options, use HTTPS instead of SSH to connect with your repository or add the workaround described in the previous comment.

I was able to configure Gitium via SSH using the Dockerfile below:

```
FROM docker.io/bitnami/wordpress:5

USER 0
RUN install_packages git ssh
RUN echo "wordpress:x:$(id -g):" >> /etc/groups
RUN echo "wordpress:x:1001:$(id -g):Wordpress:$WORDPRESS_HOME:/bin/false" >> /etc/passwd
USER 1001
```

**Comment by himanshuahuja96** [comment]
Thank you! @migruiz4 

**First**

It is now connected but the git repo is having just a symbolic link.

Here is screenshot of git repo after adding connection data.

![image](https://user-images.githubusercontent.com/18248507/121537022-2f3a1800-ca21-11eb-948a-43e00963f8b2.png)

`/bitnami/wordpress/wp-content`

**Second:**

I would like to use s3 bucket with uploads. So, is there is a way to just store plugins, themes and language file in Persistant disk?

**Comment by migruiz4** [comment]
Hi,

Answering your questions:

**First question**

I'm not familiar with the `Gitium` plugin, so I can't really tell if it is expected behavior or not.
For further questions, I'd recommend checking the Gitium Support forum: https://wordpress.org/support/plugin/gitium/

**Second Question**

I'm not really sure I fully understand what you mean. 
But the Bitnami Worpress image persists the `wp-content` folder and WordPress configuration file (`wp-config.php`) when mounting a volume at `/bitnami/wordpress`.
Plugins, themes, uploads and languages are stored in wp-content and therefore persisted if a volume is properly configured.

> I would like to use s3 bucket with uploads.

This is what I don't know exactly what you mean. 
The Bitnami Worpress Image has W3 Total Cached already installed which can be configured to use Amazon S3 as your CDN: https://github.com/W3EDGE/w3-total-cache/wiki/FAQ:-CDN#how-do-i-configure-amazon-simple-storage-service-amazon-s3-or-amazon-cloudfront-as-my-cdn

Here you can find an user with a similar inquiry to yours which you might find helpful: https://wordpress.org/support/topic/w3-total-cache-aws-cdn-s3-integration/ 

If that does not fulfill your requirements maybe there is another Wordpress plugin that does.

I'm sorry I can not be more helpful. If you find any issues with the Bitnami Wordpress image during your configuration please let me know.
