### ISSUE TITLE
Env var WORDPRESS_DATA_TO_PERSIST:  ' ' uses default values.

### ISSUE THREAD

**Issue by EarthlingDavey** [bitnami/bitnami-docker-wordpress#309]
**Description**

To have no persistant data, I assume `WORDPRESS_DATA_TO_PERSIST:  ' '` shold work. But, instead it reverts to the default value of `wp-config.php wp-content`

**Steps to reproduce the issue:**

1. 
```
docker run -d --name wordpress \
  # ...
  --env WORDPRESS_DATA_TO_PERSIST:  ' '
```

**Describe the results you received:**

Check the /bitnami/wordpress directory of the container. It has `wp-config.php` and `wp-content`

**Describe the results you expected:**

Check the /bitnami/wordpress directory of the container. It should be empty.

**Additional information you deem important (e.g. issue happens only occasionally):**

A temporary work around, is to have a single space `WORDPRESS_DATA_TO_PERSIST:  '  '`

**Comment by pablogalegoc** [comment]
Hi @EarthlingDavey!

Yes, this is the "normal" behaviour. It comes from here:
https://github.com/bitnami/bitnami-docker-wordpress/blob/afc08cde3bab4be20fa17fb9f19fe3211cec2864/5/debian-10/rootfs/opt/bitnami/scripts/wordpress-env.sh#L106
That `:-` is used to set `WORDPRESS_DATA_TO_PERSIST` to `"wp-config.php wp-content"` in case `WORDPRESS_DATA_TO_PERSIST` is unset or null ([Shell parameter expansion](http://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html)). That's why `" "` works but `""` not.

We should probably update the README to note this behaviour. Thanks for flagging it!

**Comment by EarthlingDavey** [comment]
Hi @pablogalegoc - thank you for explaining. 

I proposed the above PR :)

**Comment by pablogalegoc** [comment]
Thank you @EarthlingDavey, I think this little trick is going to save people's time!

**Comment by EarthlingDavey** [comment]
No problem, I hope so. Cheers and thank you @pablogalegoc @carrodher ✌️
