### ISSUE TITLE
setup Bedrock file structure with bitnami

### ISSUE THREAD

**Issue by koraysels** [bitnami/bitnami-docker-wordpress#325]
Can we use a custom folder structure with the bitnami image? (through AWS lightsail)

we use [bedrock](https://roots.io/bedrock/) in all our projects and are looking to deploy on AWS lightsail wordpress app

**Comment by migruiz4** [comment]
Hi @koraysels,

I'm not familiar with bedrock and helping configure it would be out of my scope, but I would recommend starting by having a look at the WordPress environment variables that you may need to change:
https://github.com/bitnami/bitnami-docker-wordpress/blob/a959b009e34c86b4c570320e6b6bb3d111421d94/5/debian-10/rootfs/opt/bitnami/scripts/wordpress-env.sh#L96-L106

And you might probably need to build your custom image changing the WordPress `postunpack.sh` script:
https://github.com/bitnami/bitnami-docker-wordpress/blob/a959b009e34c86b4c570320e6b6bb3d111421d94/5/debian-10/rootfs/opt/bitnami/scripts/wordpress/postunpack.sh#L33-L45

This may be optional as far as you set the correct permissions.

Also please keep in mind we may not be able to help you with issues caused by image customizations.
