### ISSUE TITLE
Cant' setup variable WORDPRESS_TABLE_PREFIX to empty

### ISSUE THREAD

**Issue by UnderFenex** [bitnami/bitnami-docker-wordpress#328]
When setting the variable WORDPRESS_TABLE_PREFIX = "", the containter get the value:
WORDPRESS_TABLE_PREFIX = "wp_"

Is there a workaround?

**Comment by carrodher** [comment]
Unfortunately, this is not possible due to this line:

https://github.com/bitnami/bitnami-docker-wordpress/blob/09df28a5e3d0fb61eb3e8fec4c070faaf3d2fae4/5/debian-10/rootfs/opt/bitnami/scripts/wordpress-env.sh#L116

If the `WORDPRESS_TABLE_PREFIX` env. variable is not set (aka is empty or _null_) it uses a default value (`wp_`). This is a good practice to differentiate between different apps, WP instances, etc in the database.

As a workaround, you can remove the default value from the above sentence and build your own image:
```diff
-export WORDPRESS_TABLE_PREFIX="${WORDPRESS_TABLE_PREFIX:-wp_}" # only used during the first initialization
+export WORDPRESS_TABLE_PREFIX="${WORDPRESS_TABLE_PREFIX}" # only used during the first initialization
```
```
$ git clone https://github.com/bitnami/bitnami-docker-wordpress.git
$ cd bitnami-docker-wordpress/5/debian-10
$ vim rootfs/opt/bitnami/scripts/wordpress-env.sh ## Apply above changes
$ docker build . -t REPO/my-wordpress
```
and then use your custom `REPO/my-wordpress` container image (previously pushed to a container registry if needed)

**Comment by UnderFenex** [comment]
Thanks @carrodher !
