### ISSUE TITLE
Run Wordpress with a readonly filesystem

### ISSUE THREAD

**Issue by hlascelles** [bitnami/bitnami-docker-wordpress#334]
**Description**

We'd like to run Wordpress with a readonly file system to improve security. We are happy that we can load in wp-content, plugins and themes etc in the Dockerfile` build. We know this limits some Wordpress functionality like changing pages at runtime, installing plugins etc..., but that is fine.

**Steps to reproduce the issue:**

1. Set `read_only: true` in docker-compose
2. Start the container.

**Describe the results you received:**

We see errors that Wordpress cannot be "exploded"/"copied" during startup.

```
docker_context-wordpress-1  | wordpress 13:54:04.68 WARN  ==> The WordPress configuration file '/opt/bitnami/wordpress/wp-config.php' is not writable. Configurations based on environment variables will not be applied for this file.
Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
docker_context-wordpress-1  | wordpress 13:54:04.73 ERROR ==> Could not create htaccess for wordpress at '/opt/bitnami/apache/conf/vhosts/htaccess/wordpress-htaccess.conf'. Check permissions and ownership for parent directories.
```

**Describe the results you expected:**

Wordpress starts.

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens every time.

**Version**

- Output of `docker version`: Version:           20.10.9

All versions of docker/docker-compose/wordpress image

**Comment**

Does this image support a read only state? If we can "pre-explode" Wordpress during a `Dockerfile` build, we can do that with a  `FROM` of this image. That would be great.

What do other people do to comply with deploying this image in a cluster that enforces read only filesystems?

Thanks!

**Comment by miguelaeh** [comment]
Hi @hlascelles ,
> Does this image support a read only state? 

This image has not been tested with that scenario, so it is not recommended to do it. The image contains some logic to auto-configure WordPress and Apache that needs to write into the files system, if the file system is not writable it won't be able to start.

In order to achieve what you want, you would need to mount your own configuration file already configured, since the logic won't be able to write to it.
Also, you will need to set `WORDPRESS_SKIP_BOOTSTRAP` to `true` so it does not try to configure the database or install plugins, etc.
And apart from that, you will probably need to customize the apache logic (that is the one failing in your case) to avoid the issues with the htaccess file.

I am not sure if this would be a good approach for your case but maybe running the container configuring it as you need, waiting for everything to be configured, and then making a snapshot that you can carry to the the read_only platform would work.

**Comment by hlascelles** [comment]
Thank you for the detailed writeup. :+1:  We will consider our options and maybe have a go. We'll let you know what we find if we get anywhere.
