### ISSUE TITLE
Remove separate volume declarations?

### ISSUE THREAD

**Issue by prydonius** [bitnami/bitnami-docker-wordpress#96]
In https://github.com/kubernetes/charts/pull/1053 we found that each volume (`/bitnami/apache`, `/bitnami/wordpress` and `/bitnami/php`) must be mounted separately for data to be persisted properly. If you mount a single volume at `/bitnami` Docker will mount it's own ephemeral volumes over yours. I think the ideal usecase is the ability to mount a single volume for simpler cases, but separate volumes for those that may need it. To this end, we either need to

- replace volume declarations with a single one at `/bitnami`
- _or_, remove volume declarations and assume Compose, Kubernetes, etc. will handle it

I'm not 100% the first option will allow you to mount separate volumes, and the second one has the downside of data being persisted inside the container filesystem.

cc/ @sameersbn @bcorijn

**Comment by bcorijn** [comment]
I am not sure what the initial considerations were to explicitly declare those three volumes, but as far as I can think of, removing them would allow both options to work?

**Comment by jotadrilo** [comment]
I think we could do a quick investigation in order to catch any backward incompatibilities but it seems the proposed change is harmless.

I think the first option that @prydonius suggested ("replace volume declarations with a single one at `/bitnami`") will work nicely with Compose, k8s, etc. And it will also allow users to run standalone images with persistence support. Eg (`docker run bitnami/wordpress:latest`)

If we remove any volume reference in the Dockerfiles we will rely 100% on orchestration tools to allow persistence. I don't think that's the way to go since we unknown if all the container users run wordpress by running `docker` instead of compose, k8s, etc

Also, by changing this approach, current deployments will move from several mount points to only one: they will stop working without manual intervention. This will only affect again to users running `docker` instead of an orchestration tool. Those tools will mount the specific volumes on top of the container's one so there are not manual intervention in place to make it work.

@prydonius do you think I missed something? We should evaluate the implications of this change. It seems reasonable to go ahead, though.

**Comment by sameersbn** [comment]
@jotadrilo @prydonius I am in favour of unifying all the volumes under `/bitnami` and suggest removing the `VOLUME` declarations from the Dockerfile. Let's use a single mount point at the `/bitnami` path in the `docker-compose.yml` and the readme snippets.

**Comment by prydonius** [comment]
@jotadrilo @sameersbn sounds good, let's go ahead with that then

**Comment by stonegatebi** [comment]
I spent a good 8 hours trying to investigate and eventually solve the issues being discussed.  The README.md explains the ideal way to persist data is to map from wordpress-data:/bitnami, but alas the 3  ephemeral volumes showed up; nothing visible in a Dockerfile or script that I could find.

Please correct the README.md and tell people that they need to either create bind or named volume mounts for   php-data:/bitnami/php, apache-conf:/bitnami/apache, and wordpress-data:/bitnami/wordpress

I suspect 3 separate volumes are more portable than one mount.  This way your mechanisms developed for the other stand alone components can remain the same.  No matter what, I'll end up with a compose file and probably a wordpress-custom-Dockerfile to do last mile configs and file placements.
I would be more interested in seeing the team use new features in 3.3 like 'configs' and 'secrets' for initialization.  You can do like mysql did, and take in environment variables that specify a secret or configs path, and let docker swarm / stack make it all hum.

Thanks for your work.

**Comment by sameersbn** [comment]
> I spent a good 8 hours trying to investigate and eventually solve the issues being discussed

I am very sorry to hear that you had to spend so much time to start using our wordpress image. In the future please do not hesitate to reach out to us directly on [slack](http://slack.oss.bitnami.com/) to help you resolve issues faster.

>  the 3 ephemeral volumes showed up; nothing visible in a Dockerfile or script that I could find.

@stonegabi The `VOLUME` declarations were removed from the `Dockerfile` since release `4.8.0-r2`. I suspect you may be working with an older release of the `bitnami/wordpress` image which has `VOLUME` declarations for the 3 mount paths. If you are using the `bitnami/wordpress:latest` image, could you please retry after updating the image with `docker pull bitnami/wordpress:latest` or if you're using docker-compose then `docker-compose pull`.

> I suspect 3 separate volumes are more portable than one mount.

Since we have removed the VOLUME instruction from the Dockerfile, the user is free to choose between mounting a single volume at `/bitnami` or three separate volumes. 

> I would be more interested in seeing the team use new features in 3.3 like 'configs' and 'secrets' for initialization

I completely agree with you on this. We will investigate these configuration options and have them ready for use ASAP.

**Comment by sameersbn** [comment]
this issue has been resolved.
