### ISSUE TITLE
Update to PHP latest

### ISSUE THREAD

**Issue by delmicio** [bitnami/bitnami-docker-wordpress#99]
Why not just use bitnami-docker-php-fpm as base?

**Comment by chipironcin** [comment]
Hi @delmicio 
The Bitnami PHP-FPM container is updated with latest versions of PHP, but the reason why Bitnami WordPress container is not based on Bitnami PHP-FPM container is to avoid incompatibilities with latest versions. If we update Bitnami PHP-FPM container and base WordPress container on it, WordPress version may not be compatible with that latest version of PHP.

With Bitnami WordPress container we ship the latest version of WordPress with a more or less up to date version of underlying components. The main goal is to keep WordPress up to date and working. On every Bitnami WordPress container release we update its base components to the latest compatible version.

In the future, we plan to release new revisions of this image every time we detect new versions of any underlying component.

Why is it valuable to you having the latest PHP version in the Bitnami WordPress container?

**Comment by delmicio** [comment]
@chipironcin Nothing in particular, just to start my project using the best technologies there are. I really like bitnami containers and this one surprised me a bit because of this 2 major version behind.

I understand why now. Thank you.

**Comment by chipironcin** [comment]
Oh, you are right, we are using PHP5.6
My comment applies to versions inside specific branches.
So currently we update the PHP version to latest from branch 5.6 each time we update WordPress version.

The real reason why we are not using PHP7 or PHP7.1 is because even though WordPress is ready for (and now recommends) PHP7, some plugins might not work yet.

We plan to update PHP in Bitnami WordPress container from 5.6 branch to 7 or even 7.1 branch soon.

Meanwhile, you can just modify the Dockerfile and set a newer version of PHP, removing the checksum or copying the whole line from `https://github.com/bitnami/bitnami-docker-php-fpm/blob/master/7.0/Dockerfile`. Build it like `bitnami/wordpress:latest` and launch the docker-compose ;)

Example, in `https://github.com/bitnami/bitnami-docker-wordpress/blob/master/4/Dockerfile`
```
-RUN bitnami-pkg unpack php-5.6.30-3 --checksum af6c238825d4394fc6352c5ad48c1e6423e21520df927097dab592f0d4ad4662
+RUN bitnami-pkg unpack php-7.0.20-0 --checksum 78181d1320567be07448e75e4783ce0269b433fc9e7ed8eff67abcff7f7327e9
```

Hope this helps ;)
